version: '3.8'

services:
  php:
    image: php:7.2-fpm
    build:
      context: .
      dockerfile: dockerfile
    container_name: php-freshcube
    volumes:
      - .:/var/www/html
      - ./php.ini:/usr/local/etc/php/php.ini
    working_dir: /var/www/html
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    container_name: mysql-freshcube
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel_user
      MYSQL_PASSWORD: laravel_password
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"

  nginx:
    image: nginx:latest
    container_name: nginx-freshcube
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

volumes:
  mysql_data:

